from setuptools import setup
setup(name='PMUforecast',
version='0.1',
description='Testing installation of Package',
url='#',
author='Armin',
author_email='aalig002@ucr.edu',
license='MIT',
packages=['PMUforecast'],
install_requires=[
    'setuptools',
    'markdown',
    'numpy',
    'tensorflow',
    'pandas',
    'matplotlib',
    'datetime',
    'solcast',
    # 'json',
    # 'time',
    # 'urllib',
    'solcast',
    # 'random',
    'opencage',
    'sklearn',    
    
      ],
zip_safe=False)
